# Generated by Django 6.0 on 2026-01-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="interests",
            field=models.TextField(
                blank=True, help_text="Comma-separated interests", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_onboarded",
            field=models.BooleanField(
                default=False, help_text="Has the user completed the setup flow?"
            ),
        ),
    ]
