# Generated by Django 6.0 on 2026-01-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_interests_user_is_onboarded"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="allow_profile_autofill",
            field=models.BooleanField(
                default=True,
                help_text="Allow event registrations to pre-fill from profile (can be disabled)",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="degree",
            field=models.CharField(
                blank=True, help_text="e.g. B.Tech CSE, MBA", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="dietary_preferences",
            field=models.CharField(
                blank=True,
                help_text="Vegetarian, Vegan, etc.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="emergency_contact_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="emergency_contact_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="experience_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                    ("expert", "Expert"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="github_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="graduation_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="institution",
            field=models.CharField(
                blank=True,
                help_text="University/Organization",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="linkedin_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="portfolio_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="resume_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="skills",
            field=models.JSONField(
                blank=True, default=list, help_text="List of technical skills"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tshirt_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("XS", "XS"),
                    ("S", "S"),
                    ("M", "M"),
                    ("L", "L"),
                    ("XL", "XL"),
                    ("XXL", "XXL"),
                ],
                max_length=5,
                null=True,
            ),
        ),
    ]
