# Generated by Django 6.0 on 2026-01-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_allow_profile_autofill_user_degree_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="availability",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of availability modes (learning, contributing, etc.)",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="domains",
            field=models.JSONField(
                blank=True, default=list, help_text="List of domains user is active in"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="intent",
            field=models.TextField(
                blank=True,
                help_text="Why are you here? (Personal Mission Statement)",
                null=True,
            ),
        ),
    ]
