# Generated by Django 5.2.8 on 2025-11-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="certificate",
            name="pdf_url",
        ),
        migrations.AddField(
            model_name="certificate",
            name="pdf",
            field=models.FileField(blank=True, null=True, upload_to="certificates/"),
        ),
    ]
