# Generated by Django 5.2.8 on 2025-12-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_remove_certificate_pdf_url_certificate_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="cert_token",
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
