# Generated by Django 5.2.8 on 2025-12-06 10:34

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_certificate_cert_token"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="cert_token",
            field=models.CharField(
                blank=True, db_index=True, max_length=128, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="eventattendance",
            name="qr_code",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(fields=["registration"], name="cert_registration_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["organizer", "start_time"], name="event_org_start_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["start_time"], name="event_start_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["created_at"], name="event_created_idx"),
        ),
        migrations.AddIndex(
            model_name="eventattendance",
            index=models.Index(fields=["qr_code"], name="att_qr_code_idx"),
        ),
        migrations.AddIndex(
            model_name="eventattendance",
            index=models.Index(fields=["registration"], name="att_registration_idx"),
        ),
        migrations.AddIndex(
            model_name="eventregistration",
            index=models.Index(
                fields=["event", "registered_at"], name="reg_event_registered_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventregistration",
            index=models.Index(fields=["user", "event"], name="reg_user_event_idx"),
        ),
    ]
