# Generated by Django 5.2.8 on 2025-12-06 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_alter_certificate_cert_token_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScanLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qr_code", models.CharField(max_length=128)),
                ("ip_address", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("check_in", "Check-in"),
                            ("check_out", "Check-out"),
                            ("invalid_qr", "Invalid QR"),
                            ("unauthorized", "Unauthorized"),
                            ("already_completed", "Already completed"),
                        ],
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_logs",
                        to="events.event",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scan_logs",
                        to="events.eventregistration",
                    ),
                ),
                (
                    "scanned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scan_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["event", "created_at"], name="scanlog_event_created_idx"
                    ),
                    models.Index(fields=["qr_code"], name="scanlog_qrcode_idx"),
                    models.Index(
                        fields=["action", "created_at"],
                        name="scanlog_action_created_idx",
                    ),
                ],
            },
        ),
    ]
