# Generated by Django 5.2.8 on 2025-12-06 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_announcement_options_alter_feeditem_options_and_more"),
        ("events", "0007_eventfeedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="community",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="core.community",
            ),
        ),
    ]
