# Generated by Django 5.2.8 on 2025-12-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_eventteammember"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="approved",
                max_length=32,
            ),
        ),
    ]
