# Generated by Django 6.0 on 2026-01-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_event_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="currency",
            field=models.CharField(default="INR", max_length=10),
        ),
        migrations.AddField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("workshop", "Workshop"),
                    ("seminar", "Seminar"),
                    ("fest", "Fest"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="location_lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="location_lng",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="event",
            name="waitlist_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="eventfeedback",
            name="is_anonymous",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="payment_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("refunded", "Refunded"),
                    ("skipped", "Skipped"),
                ],
                default="pending",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("waitlisted", "Waitlisted"),
                    ("rejected", "Rejected"),
                    ("canceled", "Canceled"),
                    ("attended", "Attended"),
                ],
                default="pending",
                max_length=32,
            ),
        ),
    ]
