# Generated by Django 6.0 on 2026-01-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0011_event_currency_event_event_type_event_is_paid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="media_image",
            field=models.ImageField(
                blank=True,
                help_text="Optional image for visual updates (Instagram-style).",
                null=True,
                upload_to="events/announcements/",
            ),
        ),
    ]
