# Generated by Django 6.0 on 2026-01-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0012_announcement_media_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="attendee_name_snapshot",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="certificate",
            name="event_date_snapshot",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="certificate",
            name="event_title_snapshot",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="certificate",
            name="issuer_name_snapshot",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="certificate",
            name="revocation_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="certificate",
            name="revoked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eventattendance",
            name="device_fingerprint",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="eventattendance",
            name="last_scan_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eventattendance",
            name="qr_security_token",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
