# Generated by Django 6.0 on 2026-01-03 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0013_certificate_attendee_name_snapshot_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="certificate",
            name="attendee_name_snapshot",
        ),
        migrations.RemoveField(
            model_name="certificate",
            name="event_date_snapshot",
        ),
        migrations.RemoveField(
            model_name="certificate",
            name="event_title_snapshot",
        ),
        migrations.RemoveField(
            model_name="certificate",
            name="issuer_name_snapshot",
        ),
        migrations.RemoveField(
            model_name="certificate",
            name="revocation_reason",
        ),
        migrations.RemoveField(
            model_name="certificate",
            name="revoked_at",
        ),
        migrations.RemoveField(
            model_name="eventattendance",
            name="device_fingerprint",
        ),
        migrations.RemoveField(
            model_name="eventattendance",
            name="last_scan_at",
        ),
        migrations.RemoveField(
            model_name="eventattendance",
            name="qr_security_token",
        ),
    ]
