# Generated by Django 6.0 on 2026-01-03 07:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0014_remove_certificate_attendee_name_snapshot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="credential_id",
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name="certificate",
            name="issuer_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="certificate",
            name="revocation_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="certificate",
            name="revoked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(fields=["credential_id"], name="cert_credential_img"),
        ),
    ]
