# Generated by Django 6.0 on 2026-01-03 07:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0015_certificate_credential_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="credential_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
