# Generated by Django 6.0 on 2026-01-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0017_certificate_content_type_certificate_object_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventregistration",
            name="custom_responses",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Answers to event-specific questions",
            ),
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="snapshot_degree",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="snapshot_dietary",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="snapshot_emergency_contact",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="snapshot_emergency_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="snapshot_graduation_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="snapshot_institution",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="snapshot_skills",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="snapshot_tshirt_size",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
