# Generated by Django 6.0 on 2026-01-03 09:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0018_eventregistration_custom_responses_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "invite_token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "max_size",
                    models.IntegerField(default=4, help_text="Maximum team members"),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False, help_text="Prevent new members from joining"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "skills_needed",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Skills the team is looking for",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_teams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["event", "created_at"], name="team_event_created_idx"
                    ),
                    models.Index(fields=["invite_token"], name="team_invite_idx"),
                ],
                "unique_together": {("event", "name")},
            },
        ),
    ]
