# Generated by Django 6.0 on 2026-01-03 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0019_eventteam"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ParticipantTeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("leader", "Team Leader"), ("member", "Member")],
                        default="member",
                        max_length=20,
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        blank=True,
                        help_text="Auto-created if user joins via invite link",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.eventregistration",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="events.eventteam",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["team", "joined_at"], name="ptm_team_joined_idx"
                    )
                ],
                "unique_together": {("team", "user")},
            },
        ),
    ]
