# Generated by Django 6.0 on 2026-02-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0021_eventvolunteer"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventregistration",
            name="guests_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of additional guests attending"
            ),
        ),
    ]
