# Generated by Django 5.2.8 on 2025-12-06 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_community_communitymembership_and_more"),
        ("events", "0007_eventfeedback"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="announcement",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="feeditem",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="announcement",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="core_announcements",
                to="events.event",
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="organizer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="core_announcements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="feeditem",
            name="announcement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feed_items",
                to="core.announcement",
            ),
        ),
        migrations.AlterField(
            model_name="feeditem",
            name="certificate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feed_items",
                to="events.certificate",
            ),
        ),
        migrations.AlterField(
            model_name="feeditem",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feed_items",
                to="events.event",
            ),
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["created_at"], name="core_announcement_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feeditem",
            index=models.Index(fields=["created_at"], name="feeditem_created_idx"),
        ),
        migrations.AddIndex(
            model_name="feeditem",
            index=models.Index(fields=["type"], name="feeditem_type_idx"),
        ),
    ]
