# Generated by Django 5.2.8 on 2025-12-06 13:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_announcement_options_alter_feeditem_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="communitymembership",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="If True, this is the user's active/default community.",
            ),
        ),
        migrations.AddField(
            model_name="communitymembership",
            name="last_active_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time this community was set as active for the user.",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="communitymembership",
            index=models.Index(
                fields=["user", "is_default"], name="membership_user_default_idx"
            ),
        ),
    ]
