# Generated by Django 5.2.8 on 2025-12-06 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_communitymembership_is_default_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunityInvite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        help_text="Opaque token used to join this community via invite.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        default="member",
                        help_text="Role the joining user will receive.",
                        max_length=32,
                    ),
                ),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum number of times this invite can be used. Null = unlimited.",
                        null=True,
                    ),
                ),
                ("used_count", models.PositiveIntegerField(default=0)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="If set, invite becomes invalid after this time.",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="If false, invite cannot be used even if not expired.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites",
                        to="core.community",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_community_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["token"], name="community_invite_token_idx")
                ],
            },
        ),
    ]
