# Generated by Django 5.2.8 on 2025-12-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_communityinvite"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="certificate_template",
            field=models.ImageField(
                blank=True,
                help_text="Optional certificate background/template image",
                null=True,
                upload_to="communities/cert_templates/",
            ),
        ),
        migrations.AddField(
            model_name="community",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Community logo used in UI & certificates",
                null=True,
                upload_to="communities/logos/",
            ),
        ),
        migrations.AddField(
            model_name="community",
            name="primary_color",
            field=models.CharField(
                blank=True, help_text="Primary HEX color (e.g. #FF5733)", max_length=7
            ),
        ),
    ]
