# Generated by Django 6.0 on 2026-01-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_feedcomment_feedlike"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="is_private",
            field=models.BooleanField(
                default=False,
                help_text="If True, community content is hidden from non-members.",
            ),
        ),
    ]
