# Generated by Django 6.0 on 2026-01-03 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0008_community_is_private"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DomainActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verb", models.CharField(db_index=True, max_length=64)),
                ("object_id", models.PositiveIntegerField()),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("community", "Community"),
                            ("private", "Private"),
                        ],
                        default="community",
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "community",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="core.community",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReputationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                ("reason", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reputation_effects",
                        to="core.domainactivity",
                    ),
                ),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reputation_logs",
                        to="core.community",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reputation_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserCommunityStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reputation_score", models.IntegerField(default=0)),
                ("current_level", models.IntegerField(default=1)),
                ("events_attended", models.PositiveIntegerField(default=0)),
                ("events_hosted", models.PositiveIntegerField(default=0)),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_stats",
                        to="core.community",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="domainactivity",
            index=models.Index(
                fields=["community", "created_at"],
                name="core_domain_communi_0da4a3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="domainactivity",
            index=models.Index(
                fields=["actor", "verb"], name="core_domain_actor_i_e1a1ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="domainactivity",
            index=models.Index(
                fields=["visibility", "created_at"],
                name="core_domain_visibil_2cbd82_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reputationlog",
            index=models.Index(
                fields=["user", "community"], name="core_reputa_user_id_a9a321_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usercommunitystats",
            index=models.Index(
                fields=["community", "reputation_score"],
                name="core_userco_communi_04ac82_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usercommunitystats",
            unique_together={("user", "community")},
        ),
    ]
