# Generated by Django 6.0 on 2026-01-03 07:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0009_domainactivity_reputationlog_usercommunitystats_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="reputationlog",
            name="core_reputa_user_id_a9a321_idx",
        ),
        migrations.AlterUniqueTogether(
            name="usercommunitystats",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="usercommunitystats",
            name="core_userco_communi_04ac82_idx",
        ),
        migrations.AlterModelOptions(
            name="domainactivity",
            options={
                "ordering": ["-timestamp"],
                "verbose_name_plural": "Domain Activities",
            },
        ),
        migrations.RemoveIndex(
            model_name="domainactivity",
            name="core_domain_communi_0da4a3_idx",
        ),
        migrations.RemoveIndex(
            model_name="domainactivity",
            name="core_domain_actor_i_e1a1ae_idx",
        ),
        migrations.RemoveIndex(
            model_name="domainactivity",
            name="core_domain_visibil_2cbd82_idx",
        ),
        migrations.RenameField(
            model_name="domainactivity",
            old_name="created_at",
            new_name="timestamp",
        ),
        migrations.AlterField(
            model_name="domainactivity",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="domainactivity",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("community", "Community-Only"),
                    ("private", "Private"),
                ],
                db_index=True,
                default="community",
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="domainactivity",
            index=models.Index(
                fields=["community", "-timestamp"],
                name="core_domain_communi_78b310_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="domainactivity",
            index=models.Index(
                fields=["actor", "-timestamp"], name="core_domain_actor_i_96c345_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="usercommunitystats",
            name="community",
        ),
        migrations.RemoveField(
            model_name="usercommunitystats",
            name="user",
        ),
        migrations.DeleteModel(
            name="ReputationLog",
        ),
        migrations.DeleteModel(
            name="UserCommunityStats",
        ),
    ]
