# Generated by Django 6.0 on 2026-01-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_remove_reputationlog_core_reputa_user_id_a9a321_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="domainactivity",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("revoked", "Revoked"),
                    ("deleted", "Deleted"),
                    ("superseded", "Superseded"),
                ],
                db_index=True,
                default="active",
                max_length=16,
            ),
        ),
    ]
