# Generated by Django 6.0 on 2026-01-03 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0011_domainactivity_status"),
        ("events", "0016_alter_certificate_credential_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="feeditem",
            name="activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feed_items",
                to="core.domainactivity",
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="event",
            field=models.ForeignKey(
                blank=True,
                help_text="DEPRECATED: Use GenericFK below for new modules.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="core_announcements",
                to="events.event",
            ),
        ),
    ]
