# Generated by Django 6.0 on 2026-01-03 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0010_remove_reputationlog_core_reputa_user_id_a9a321_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReputationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(help_text="Positive or negative point value"),
                ),
                (
                    "reason",
                    models.CharField(help_text="e.g. event.attended", max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reputation_impacts",
                        to="core.domainactivity",
                    ),
                ),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reputation_logs",
                        to="core.community",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reputation_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "community", "-created_at"],
                        name="gamificatio_user_id_414102_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserCommunityStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_xp", models.IntegerField(default=0)),
                ("current_level", models.IntegerField(default=1)),
                ("events_attended", models.PositiveIntegerField(default=0)),
                ("events_hosted", models.PositiveIntegerField(default=0)),
                ("last_activity_at", models.DateTimeField(auto_now_add=True)),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_stats",
                        to="core.community",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["community", "-total_xp"],
                        name="gamificatio_communi_ea6491_idx",
                    )
                ],
                "unique_together": {("user", "community")},
            },
        ),
    ]
