# Generated by Django 6.0 on 2026-01-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamification", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercommunitystats",
            name="stats",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
